import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

type Params = { params: { id: string } };

// GET /api/applicants/:id/pdf — arizachi uchun tasdiq PDF yaratib qaytaradi
export async function GET(_req: NextRequest, { params }: Params) {
  const id = Number(params.id);
  const a = await prisma.applicant.findUnique({
    where: { id },
    include: { group: true },
  });
  if (!a) return NextResponse.json({ error: "Topilmadi" }, { status: 404 });

  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]); // A4
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const navy = rgb(0.1, 0.16, 0.55);
  const gray = rgb(0.3, 0.3, 0.3);

  // Sarlavha
  page.drawRectangle({ x: 0, y: 782, width: 595, height: 60, color: navy });
  page.drawText("APPOINTMENT CONFIRMATION", {
    x: 40,
    y: 805,
    size: 18,
    font: bold,
    color: rgb(1, 1, 1),
  });

  const lines: [string, string][] = [
    ["Group", a.group.name],
    ["Reference", a.appointmentRef || `APP-${a.id}`],
    ["Status", a.status],
    ["Surname", a.surname],
    ["Name", a.name],
    ["Passport", a.passportNumber],
    ["Nationality", a.nationality || "-"],
    ["Gender", a.gender || "-"],
    ["Birthdate", a.birthdate || "-"],
    ["Passport validity", a.passportValidity || "-"],
    ["Phone", a.phone || "-"],
    ["Email", a.email || "-"],
    ["Subcategory", a.subcategory || "-"],
    ["Issued", new Date().toLocaleString("en-GB")],
  ];

  let y = 740;
  for (const [label, value] of lines) {
    page.drawText(`${label}:`, { x: 40, y, size: 11, font: bold, color: gray });
    page.drawText(value, { x: 200, y, size: 11, font, color: rgb(0, 0, 0) });
    y -= 26;
  }

  page.drawText("Generated by Visa CRM", {
    x: 40,
    y: 40,
    size: 9,
    font,
    color: gray,
  });

  const bytes = await pdf.save();

  return new NextResponse(Buffer.from(bytes), {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="appointment-${a.id}.pdf"`,
    },
  });
}
